swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Cliente API'
  description: ' | 
    Esta api tem por objetivo cadastrar, consultar, alterar e excluir clientes.
    [Saiba mais]()
  '
consumes:
  - application/json
  
produces: 
  - application/json
  
tags:
  - name: 'Consulta'
  - name: 'Cadastro'
  - name: 'Atualizacao'
  - name: 'Exclusao'
  - name: 'API'
  
# localhost:8080/clients-api/v1
host: localhost:8080
basePath: /clients-api/v1
schemes: 
  - http
  - https
  
paths: 
  # localhost:8080/clients-api/v1/clients
  /clients:
    get:
      tags: 
        - Consulta
      summary: 'Consulta todos os clientes.'
      operationId: 'findAll'
      description: 'Esta operação tem por objetivo consultar todos os clientes.'
      responses:
        200:
          description: 'Sucesso ao consultar todos os clientes.'
          schema:
            $ref: '#/definitions/Clients'
        400:
          description: 'Consulta inválida.'
        401:
          description: 'Consulta não autorizada.'
        404:
          description: 'Nenhum cliente encontrado para a consulta.'
        500:
          description: 'Erro interno ao tentar realizar a consulta.'
    
    post:  
      tags: 
        - Cadastro
      summary: 'Cadastro de um novo cliente.'
      operationId: 'create'
      description: 'Esta operação tem por objetivo cadastrar um novo cliente.'
      parameters:
        - in: "body"
          name: "client"
          required: true
          schema:
            $ref: "#/definitions/Client"
      responses:
        201:
          description: 'Sucesso ao cadastrar um novo cliente.'
          schema:
            $ref: '#/definitions/Client'
          headers:
              Location: 
                type: "string"
                description: "URI do cliente cadastrado."
        400:
          description: 'Cadastro inválido.'
        401:
          description: 'Cadastro não autorizado.'
        500:
          description: 'Erro interno ao tentar realizar o cadastro.'
          
  /clients/{id}:
    put:  
        tags: 
          - Atualizacao
        summary: 'Atualiza um cliente existente.'
        operationId: 'update'
        description: 'Esta operação tem por objetivo atualizar um cliente existente.'
        parameters:
          - in: "path"
            name: "id"
            type: "integer"
            format: "int32"
            required: true
            description: "Id do cliente"
            
          - in: "body"
            name: "client"
            required: true
            schema:
              $ref: "#/definitions/Client"
        responses:
          200:
            description: 'Sucesso ao atualizar um cliente existente.'
            schema:
              $ref: '#/definitions/Client'
            headers:
              Location: 
                type: "string"
                description: "URI do cliente atualizado."
          400:
            description: 'Atualização inválida.'
          401:
            description: 'Atualização não autorizada.'
          500:
            description: 'Erro interno ao tentar realizar a atualização.'
          
    get:  
        tags: 
          - Consulta
        summary: 'Consulta um cliente existente por id.'
        operationId: 'findById'
        description: 'Esta operação tem por objetivo consultar um cliente existente por id.'
        parameters:
          - in: "path"
            name: "id"
            type: "integer"
            format: "int32"
            required: true
            description: "Id do cliente"
        responses:
          200:
            description: 'Sucesso ao consultar um cliente existente por id.'
            schema:
              $ref: '#/definitions/Client'
          400:
            description: 'Consulta inválida.'
          401:
            description: 'Consulta não autorizada.'
          404:
            description: 'Nenhum cliente encontrado para a consulta por id.'
          500:
            description: 'Erro interno ao tentar realizar a consulta por id.'
            
    delete:  
        tags: 
          - Exclusao
        summary: 'Exclui um cliente existente por id.'
        operationId: 'deleteById'
        description: 'Esta operação tem por objetivo excluir um cliente existente por id.'
        parameters:
          - in: "path"
            name: "id"
            type: "integer"
            format: "int32"
            required: true
            description: "Id do cliente"
        responses:
          204:
            description: 'Sucesso ao excluir um cliente existente por id.'
          400:
            description: 'Exclusão inválida.'
          401:
            description: 'Exclusão não autorizada.'
          404:
            description: 'Nenhum cliente encontrado para a exclusão por id.'
          500:
            description: 'Erro interno ao tentar realizar a exclusão por id.'
            
  /clients/{id}/status/{status}:
    put:  
        tags: 
          - Atualizacao
        summary: 'Atualiza o status de um cliente existente.'
        operationId: 'updateStatus'
        description: 'Esta operação tem por objetivo atualizar o status de um cliente existente.'
        parameters:
          - in: "path"
            name: "id"
            type: "integer"
            format: "int32"
            required: true
            description: "Id do cliente"
            
          - in: "path"
            name: "status"
            type: "string"
            enum: ["active", "inactive"]
            required: true
            description: "Novo status do cliente"
            
        responses:
          200:
            description: 'Sucesso ao atualizar o status de um cliente existente.'
            schema:
              $ref: '#/definitions/Client'
            headers:
              Location: 
                type: "string"
                description: "URI do cliente com status atualizado."
          400:
            description: 'Atualização de status de cliente inválida.'
          401:
            description: 'Atualização de status de cliente não autorizada.'
          500:
            description: 'Erro interno ao tentar realizar a atualização de status de cliente.'
            
  /clients/find:
    get:  
        tags: 
          - Consulta
        summary: 'Consulta clientes existentes.'
        operationId: 'find'
        description: 'Esta operação tem por objetivo consultar clientes existentes.'
        parameters:
          - in: "query"
            name: "lastName"
            type: "string"
            required: false
            description: "Sobrenome do cliente"
            
        responses:
          200:
            description: 'Sucesso ao consultar clientes existentes.'
            schema:
              $ref: '#/definitions/Clients'
          400:
            description: 'Consulta inválida.'
          401:
            description: 'Consulta não autorizada.'
          404:
            description: 'Nenhum cliente encontrado para a consulta.'
          500:
            description: 'Erro interno ao tentar realizar a consulta.'
  
  /readme:
    get:
      tags:
        - API
      summary: "Recupera readme da API"
      operationId: "readme"
      description: "Esta operação retorna o readme da API."
      responses:
        200:
          description: "Sucesso ao recuperar o readme da API."
          schema:
            type: "string"
        500:
          description: "Erro interno ao tentar recuperar o readme da API."
  
definitions: 
  Clients:
    type: array
    items:
      $ref: "#/definitions/Client"
  
  Client: 
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32" #long
        description: "Identificador do cliente."
      name: 
        type: "string"
        description: "Nome do cliente."
      lastName:
        type: "string"
        description: "Sobrenome do cliente."
      initials:
        type: "string"
        minLength: 2
        maxLength: 7
        description: "Iniciais do nome completo do cliente."
      birthDate:
        type: "string"
        format: "date"
        description: "Data de nascimento do cliente."
      lastUpdate:
        type: "string"
        format: "date-time"
        description: "Data de atualização dos dados do cliente."
      status:
        type: "boolean"
        description: "Status ativo ou inativo do cliente."
      type:
        type: "string"
        enum: ["INTERN", "EXTERN"]