/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-02-16T12:44:13.813Z")

@Validated
@Api(value = "readme", description = "the readme API")
@RequestMapping(value = "/clients-api/v1")
public interface ReadmeApi {

    @ApiOperation(value = "Recupera readme da API", nickname = "readme", notes = "Esta operação retorna o readme da API.", tags = {"API",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Sucesso ao recuperar o readme da API."),
            @ApiResponse(code = 500, message = "Erro interno ao tentar recuperar o readme da API.")})
    @RequestMapping(value = "/readme",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<String> readme();

}
